/** 분야 안내 문구의 근거 자료 목록 (2026.10.02 확인). 화면에는 표시하지 않고, 문구를 고칠 때 확인용으로 둔다. */
export const contentSources = {
  adContent: { title: "국가법령정보센터 · 의료법 제56조", url: "https://law.go.kr/lsLinkCommonInfo.do?chrClsCd=010202&lsJoLnkSeq=1018923417", scope: "치료 효과 오인·거짓·과장 등 금지되는 의료광고 내용" },
  closureNotice: { title: "국가법령정보센터 · 의료법 시행규칙 제30조의3", url: "https://law.go.kr/lsLinkCommonInfo.do?lspttninfSeq=61712", scope: "휴폐업 신고예정일 기준 안내문 게시와 입원환자 안내 기한" },
  records: { title: "국가법령정보센터 · 의료법 시행규칙 제30조", url: "https://www.law.go.kr/LSW/lsInfoP.do?ancYnChk=0&chrClsCd=010202&efYd=20260612&lsiSeq=286963&urlMode=lsInfoP", scope: "휴폐업 신고와 진료기록 직접 보관 절차" },
  planning: { title: "오픈닥터 · 개원 준비 타임라인 ①", url: "https://www.opndoctor.com/content/opening-guide-03", scope: "업체 선정, 설계·견적 비교, 준비 순서" },
  construction: { title: "오픈닥터 · 개원 준비 타임라인 ②", url: "https://www.opndoctor.com/content/opening-guide-04", scope: "공사와 장비·통신·홍보 준비의 연계" },
  opening: { title: "오픈닥터 · 개원 준비 타임라인 ③", url: "https://www.opndoctor.com/content/opening-guide-05", scope: "개원 전 현장 세팅과 운영 준비" },
  lease: { title: "오픈닥터 · 임대차 계약 전 매물 체크리스트", url: "https://www.opndoctor.com/content/opening-guide-08", scope: "건물·설비·임대인 협의 항목" },
  registration: { title: "정부24 · 의료기관 개설신고 또는 변경신고", url: "https://www.gov.kr/mw/AA020InfoCappView.do?CappBizCD=14600000065&HighCtgCD=A06004", scope: "의원급 개설신고 대상과 절차" },
  hira: { title: "정부24 · 요양기관 현황신고", url: "https://m.gov.kr/mw/AA020InfoCappView.do?CappBizCD=13520000056&HighCtgCD=A06004", scope: "건강보험심사평가원에 신고하는 시설·인력 등 현황" },
  advertising: { title: "국가법령정보센터 · 의료법 제57조", url: "https://www.law.go.kr/lsLawLinkInfo.do?chrClsCd=010202&lsJoLnkSeq=1000721562", scope: "의료광고 사전심의 대상과 예외" },
  devices: { title: "식품의약품안전처 · 의료기기 구매 시 확인사항", url: "https://mfds.go.kr/brd/m_580/view.do?seq=143", scope: "의료기기 표시·허가번호와 제품 정보 조회" },
  waste: { title: "한국환경공단 Allbaro · 의료폐기물 처리 흐름", url: "https://www.allbaro.or.kr/04_wmedi/wmedi_process.vm?tabId=1", scope: "의료폐기물 전자태그와 인계·인수 관리" },
  adReview: { title: "국가법령정보센터 · 의료법 시행령 제24조", url: "https://www.law.go.kr/법령/의료법시행령/제24조", scope: "심의 대상 인터넷 매체(일평균 이용자 10만 명 기준)와 심의 면제 항목" },
  naming: { title: "국가법령정보센터 · 의료법 시행규칙 제40조~제42조", url: "https://www.law.go.kr/법령/의료법시행규칙/제40조", scope: "의료기관 명칭표시판·진료과목 표시 방법과 글자 크기" },
  signage: { title: "국가법령정보센터 · 옥외광고물법 시행령 제4조·제5조·제12조", url: "https://www.law.go.kr/법령/옥외광고물등의관리와옥외광고산업진흥에관한법률시행령/제5조", scope: "간판 허가·신고 대상과 업소별 표시 수량" },
  accessibility: { title: "국가법령정보센터 · 장애인등편의법 시행령 별표1·2", url: "https://www.law.go.kr/법령/장애인ㆍ노인ㆍ임산부등의편의증진보장에관한법률시행령", scope: "의원 등 제1종 근린생활시설의 편의시설 설치 기준(500㎡ 기준 구분)" },
  xray: { title: "국가법령정보센터 · 진단용 방사선 발생장치의 안전관리에 관한 규칙", url: "https://www.law.go.kr/법령/진단용방사선발생장치의안전관리에관한규칙", scope: "설치 신고 기한, 사용 전 검사·방어시설 검사, 정기검사, 피폭선량 측정" },
  specialEquipment: { title: "국가법령정보센터 · 특수의료장비의 설치 및 운영에 관한 규칙", url: "https://www.law.go.kr/법령/특수의료장비의설치및운영에관한규칙", scope: "CT·MRI·유방촬영장치 등록, 설치인정기준, 품질관리검사" },
  nhisReport: { title: "국가법령정보센터 · 국민건강보험법 제43조", url: "https://www.law.go.kr/법령/국민건강보험법/제43조", scope: "요양기관 시설·장비·인력 현황신고와 15일 이내 변경신고" },
  deviceLabel: { title: "국가법령정보센터 · 의료기기법 제20조", url: "https://www.law.go.kr/법령/의료기기법/제20조", scope: "의료기기 용기 기재사항(허가번호·제조번호·사용기한·일회용 표시·표준코드)" },
  singleUse: { title: "국가법령정보센터 · 의료법 제4조", url: "https://www.law.go.kr/법령/의료법/제4조", scope: "일회용 의료기기 재사용 금지(제6항)" },
  clinicOpening: { title: "국가법령정보센터 · 의료법 제33조", url: "https://www.law.go.kr/법령/의료법/제33조", scope: "의원급 개설신고(시장·군수·구청장)와 병원급 개설허가(시·도지사)" },
  clinicFacility: { title: "국가법령정보센터 · 의료법 시행규칙 제34조 별표3·별표4", url: "https://www.law.go.kr/법령/의료법시행규칙/제34조", scope: "의원 시설기준과 입원실 면적·병상 간격 등 시설규격" },
  bizRegistration: { title: "국가법령정보센터 · 부가가치세법 제8조", url: "https://www.law.go.kr/법령/부가가치세법/제8조", scope: "사업 개시일부터 20일 이내 사업자등록 신청" },
  buildingUse: { title: "국가법령정보센터 · 건축법 시행령 별표1", url: "https://www.law.go.kr/법령/건축법시행령", scope: "의원은 제1종 근린생활시설, 병원은 의료시설로 구분" },
  commercialLease: { title: "국가법령정보센터 · 상가건물 임대차보호법", url: "https://www.law.go.kr/법령/상가건물임대차보호법", scope: "대항력·확정일자, 10년 갱신요구권, 권리금 회수기회 보호, 차임 증액 상한" },
  brokerage: { title: "국가법령정보센터 · 공인중개사법 제25조·시행규칙 제20조", url: "https://www.law.go.kr/법령/공인중개사법/제25조", scope: "중개대상물 확인·설명서 교부와 주택 외 중개보수(0.9% 이내 협의)" },
  fireSafety: { title: "국가법령정보센터 · 소방시설법 시행령 별표4", url: "https://www.law.go.kr/법령/소방시설설치및관리에관한법률시행령", scope: "입원실이 있는 의원의 간이스프링클러·자동화재속보설비" },
  buildingRegister: { title: "정부24 · 건축물대장 등본(초본) 발급(열람)", url: "https://www.gov.kr/mw/AA020InfoCappView.do?CappBizCD=15000000098", scope: "후보 매물의 용도·면적·위반건축물 표시 확인" },
  wasteTypes: { title: "국가법령정보센터 · 폐기물관리법 시행령 별표2", url: "https://www.law.go.kr/법령/폐기물관리법시행령", scope: "격리·위해·일반 의료폐기물 종류와 폐백신·폐항암제·폐화학치료제 구분" },
  wasteStorage: { title: "국가법령정보센터 · 폐기물관리법 시행규칙 별표5·별표6의2", url: "https://www.law.go.kr/법령/폐기물관리법시행규칙", scope: "종류별 보관기간, 전용용기·색상, 냉장보관, 전자태그 인계·인수 입력" },
  wastePlan: { title: "국가법령정보센터 · 폐기물관리법 제17조", url: "https://www.law.go.kr/법령/폐기물관리법/제17조", scope: "의료폐기물 배출자의 처리계획 확인(사업 개시 후 1개월 이내)" },
  narcotics: { title: "국가법령정보센터 · 마약류 관리에 관한 법률 시행규칙 제23조", url: "https://www.law.go.kr/법령/마약류관리에관한법률시행규칙/제23조", scope: "사고마약류 보고와 폐기 신청·공무원 참관 폐기" },
  deviceLookup: { title: "식품의약품안전처 · 의료기기안심책방", url: "https://emedi.mfds.go.kr", scope: "의료기기 허가·인증·신고 및 표준코드(UDI) 제품 정보 조회" },
};
export type ContentSourceId = keyof typeof contentSources;
